# Generated by Django 5.0.3 on 2024-03-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('cognoms', models.CharField(max_length=30)),
                ('rol', models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], max_length=30)),
                ('correu', models.CharField(max_length=100)),
                ('curs', models.CharField(max_length=30)),
                ('moduls', models.CharField(max_length=30)),
            ],
        ),
    ]
